### ISSUE TITLE
fluides Design

### ISSUE THREAD

**Issue by Oludwig** [ThunderKey/HSR.WED3.Template.React#10]
* Die Cards auf dem Dashboard sollen im Verhalten fluid sein. Dazu können Libraries (siehe Sonstiges) verwendet werden.
* CSS Libraries (z.B. Bootstrap) dürfen eingesetzt werden. Diese müssen sich aber auf reines CSS beschränken oder explizit in der Vorlesung erwähnt/behandelt werden.

**Comment by ThunderKey** [comment]
@Oludwig ich habe im Commit 14bec7a37b5366f8f79e397bc71e813bf4ede4e3 das Layout noch ein wenig erweitert
