### ISSUE TITLE
Logout implementation

### ISSUE THREAD

**Issue by Oludwig** [ThunderKey/HSR.WED3.Template.React#5]
* Löscht das Client-seitig gespeicherte JWT Token.
* Benutzer befindet sich nach Logout auf der Welcome-Page.
* Das JWT Token aus dem Local-Storage löschen.

**Comment by ThunderKey** [comment]
Wurde direkt mit #2 in c6a35920baf05b8c796cb8df3e9c48c80f292990 umgesetzt
